'use client';

import React, { useState } from 'react';
import {
  Settings as SettingsIcon,
  Cpu,
  Sparkles,
  Send,
  Trash2,
  Code,
  X,
  ChevronDown,
  ChevronUp,
  Plus,
  FileCode,
  Download,
  Database,
  Layers,
  Layout,
  Archive,
  Terminal,
  Minimize2,
  Heart
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { AIConfig } from '@/lib/ai/provider';
import { Node, Edge } from 'reactflow';
import JSZip from 'jszip';

export default function Sidebar({
  onGenerate,
  onReset,
  config,
  setConfig,
  nodes,
  edges,
  onAddNode,
  reasoning,
  layoutDirection,
  onToggleLayout,
  onClose
}: {
  onGenerate: (prompt: string) => void;
  onReset: () => void;
  config: AIConfig;
  setConfig: (config: AIConfig) => void;
  nodes: Node[];
  edges: Edge[];
  onAddNode: (type: string) => void;
  reasoning: string | null;
  layoutDirection: 'TB' | 'LR';
  onToggleLayout: () => void;
  onClose: () => void;
  isOpen: boolean;
}) {
  const [prompt, setPrompt] = useState('');
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [isToolsCollapsed, setIsToolsCollapsed] = useState(false);

  const handleGenerate = () => {
    if (!prompt.trim()) return;
    onGenerate(prompt);
    setPrompt('');
  };

  const handleDownloadJSON = () => {
    const data = JSON.stringify({ nodes, edges, exportedAt: new Date().toISOString() }, null, 2);
    const blob = new Blob([data], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `spirit-arc-architecture-${new Date().toISOString().slice(0, 10)}.json`;
    link.click();
  };

  const handleDownloadZIP = async () => {
    const zip = new JSZip();

    // Add architecture metadata
    const structure = {
      nodes: nodes.map(n => ({ id: n.id, type: n.type, label: n.data.label })),
      edges: edges.map(e => ({ source: e.source, target: e.target, label: e.label }))
    };
    zip.file("architecture.json", JSON.stringify(structure, null, 2));

    // Create src folder and add generated code
    const srcFolder = zip.folder("src");
    if (srcFolder) {
      nodes.forEach(node => {
        if (node.data.code) {
          const filename = node.data.filename || `${node.id.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.js`;
          srcFolder.file(filename, node.data.code);
        }
      });
    }

    // Add a README
    zip.file("README.md", `# Generated Architecture: Spirit Arc\n\nThis project was generated by Spirit Arc by Mohammad Saeed Angiz.\n\n## Structure\nSee architecture.json for the full graph structure.`);

    const content = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(content);
    const a = document.createElement('a');
    a.href = url;
    a.download = `spirit-arc-project-${Date.now()}.zip`;
    a.click();
  };

  return (
    <>
      <motion.div
        className="sidebar glass"
        initial={{ x: -320, opacity: 0 }}
        animate={{ x: 0, opacity: 1 }}
        exit={{ x: -320, opacity: 0 }}
        transition={{ type: 'spring', damping: 25, stiffness: 120 }}
      >
        <div className="sidebar-header">
          <div className="logo">
            <Sparkles size={24} color="var(--primary-color)" />
            <h2>Spirit Arc</h2>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={() => setIsSettingsOpen(true)} className="icon-btn">
              <SettingsIcon size={20} />
            </button>
            <button onClick={onClose} className="icon-btn text-white/40 hover:text-white transition-colors" title="Collapse Sidebar">
              <Minimize2 size={20} />
            </button>
            <button onClick={onClose} className="icon-btn text-white/40 hover:text-white transition-colors">
              <X size={20} />
            </button>
          </div>
        </div>

        <div className="sidebar-content scrollable">
          <div className="project-info">
            <div className="info-main">
              <p className="label">Project</p>
              <h3 className="project-name">Architecture Studio</h3>
              <p className="developer-tag">By Mohammad Saeed Angiz</p>
            </div>
            <button
              onClick={() => setIsToolsCollapsed(!isToolsCollapsed)}
              className="toggle-tools-btn"
              title="Toggle Tools Section"
            >
              {isToolsCollapsed ? <ChevronDown size={18} /> : <ChevronUp size={18} />}
            </button>
          </div>

          <AnimatePresence initial={false}>
            {!isToolsCollapsed && (
              <motion.div
                className="tools-wrapper"
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                transition={{ duration: 0.3, ease: 'easeInOut' }}
              >
                <div className="prompt-section">
                  <p className="label">AI Architect</p>
                  <textarea
                    placeholder="Describe your system (e.g. 'Microservices for a shop with Redis cache')..."
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && (e.preventDefault(), handleGenerate())}
                    className="min-h-[60px] max-h-[120px]"
                  />
                  <button onClick={handleGenerate} className="generate-btn glow-hover">
                    <Send size={18} />
                    Generate
                  </button>
                </div>

                {reasoning && (
                  <div className="reasoning-section p-4 mx-4 mt-2 bg-violet-500/10 border border-violet-500/20 rounded-xl">
                    <div className="flex items-center gap-2 mb-2 text-violet-400">
                      <Cpu size={16} />
                      <span className="text-[10px] uppercase tracking-widest font-bold">Thought Process</span>
                    </div>
                    <p className="text-xs text-white/70 italic leading-relaxed max-h-[100px] overflow-y-auto pr-2 custom-scrollbar">
                      "{reasoning}"
                    </p>
                  </div>
                )}

                <div className="divider" />

                <div className="manual-tools">
                  <p className="label">Add Components</p>
                  <div className="tool-grid">
                    <button onClick={() => onAddNode('service')} className="tool-btn">
                      <Layers size={14} /> Service
                    </button>
                    <button onClick={() => onAddNode('database')} className="tool-btn">
                      <Database size={14} /> Database
                    </button>
                    <button onClick={() => onAddNode('api-gateway')} className="tool-btn">
                      <Layout size={14} /> Gateway
                    </button>
                    <button onClick={() => onAddNode('queue')} className="tool-btn">
                      <Archive size={14} /> Queue
                    </button>
                  </div>
                </div>

                <div className="divider" />

                <div className="layout-section px-4 mb-2">
                  <div className="flex items-center justify-between">
                    <p className="label m-0">Canvas Layout</p>
                    <button 
                      onClick={onToggleLayout}
                      className="flex items-center gap-2 px-3 py-1.5 bg-white/5 hover:bg-white/10 rounded-lg text-[10px] font-bold text-white transition-colors border border-white/10"
                    >
                      {layoutDirection === 'TB' ? <ChevronDown size={14} /> : <ChevronUp size={14} className="rotate-90" />}
                      {layoutDirection === 'TB' ? 'VERTICAL' : 'HORIZONTAL'}
                    </button>
                  </div>
                </div>

                <div className="actions mt-auto">
                  <p className="label">Project Controls</p>
                  <button onClick={handleDownloadZIP} className="action-btn primary-solid mb-2">
                    <FileCode size={16} />
                    Download ZIP
                  </button>
                  <div className="grid grid-cols-2 gap-2 mb-2">
                    <button onClick={handleDownloadJSON} className="action-btn secondary">
                      <Download size={14} /> JSON
                    </button>
                    <button onClick={onReset} className="action-btn danger">
                      <Trash2 size={14} /> Reset
                    </button>
                  </div>
                  <a 
                    href="https://www.paypal.com/donate/?hosted_button_id=FYKQWTSW6TL62" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="action-btn donation-btn w-full"
                  >
                    <Heart size={16} fill="currentColor" />
                    Support Project
                  </a>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        <div className="sidebar-footer">
          <a href="#" className="github-link">
            <Code size={16} />
            Source
          </a>
          <span>v1.2.0</span>
        </div>
      </motion.div>

      <AnimatePresence>
        {isSettingsOpen && (
          <motion.div
            className="modal-overlay"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setIsSettingsOpen(false)}
          >
            <motion.div
              className="modal glass"
              initial={{ scale: 0.9, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0, y: 20 }}
              onClick={e => e.stopPropagation()}
            >
              <div className="modal-header">
                <h3>AI Configuration</h3>
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    setIsSettingsOpen(false);
                  }}
                  className="close-btn"
                  aria-label="Close settings"
                >
                  <X size={20} />
                </button>
              </div>
              <div className="modal-body scrollable">
                <div className="input-group">
                  <label>Provider</label>
                  <select
                    value={config.provider}
                    onChange={e => setConfig({ ...config, provider: e.target.value as any })}
                  >
                    <option value="gemini">Google Gemini</option>
                    <option value="ollama">Ollama (Local)</option>
                    <option value="custom-openai">Custom (OpenAI Compatible)</option>
                  </select>
                </div>

                {config.provider !== 'ollama' && (
                  <div className="input-group">
                    <label>API Key</label>
                    <input
                      type="password"
                      placeholder="Enter your API Key"
                      value={config.apiKey || ''}
                      onChange={e => setConfig({ ...config, apiKey: e.target.value })}
                    />
                  </div>
                )}

                <div className="input-group">
                  <label>Base URL</label>
                  <input
                    type="text"
                    placeholder={config.provider === 'ollama' ? 'http://localhost:11434' : 'https://api.openai.com/v1'}
                    value={config.baseUrl || ''}
                    onChange={e => setConfig({ ...config, baseUrl: e.target.value })}
                  />
                </div>

                <div className="input-group">
                  <label>Model Name</label>
                  <input
                    type="text"
                    placeholder="e.g. gemini-1.5-flash, llama3, gpt-4"
                    value={config.modelName}
                    onChange={e => setConfig({ ...config, modelName: e.target.value })}
                  />
                </div>
              </div>
              <div className="modal-footer">
                <button onClick={() => setIsSettingsOpen(false)} className="save-btn glow-hover">
                  Save & Close
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <style jsx>{`
        .sidebar {
          position: fixed;
          top: 16px;
          left: 16px;
          width: 280px;
          height: calc(100vh - 32px);
          z-index: 2000;
          border-radius: 20px;
          display: flex;
          flex-direction: column;
          padding: 20px;
          box-shadow: 0 20px 50px rgba(0,0,0,0.4);
        }

        .sidebar-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 20px;
          flex-shrink: 0;
        }

        .logo {
          display: flex;
          align-items: center;
          gap: 12px;
        }

        .logo h2 {
          font-size: 20px;
          letter-spacing: -0.5px;
        }

        .icon-btn {
          color: var(--text-secondary);
          padding: 8px;
          border-radius: 10px;
          transition: all 0.2s;
        }

        .icon-btn:hover {
          background: var(--surface-accent);
          color: var(--text-primary);
        }

        .sidebar-content {
          flex: 1;
          display: flex;
          flex-direction: column;
          gap: 8px;
          overflow-x: hidden;
          padding-bottom: 10px;
        }

        .sidebar-content.scrollable {
          overflow-y: auto;
          padding-right: 4px;
        }

        .sidebar-content.scrollable::-webkit-scrollbar {
          width: 4px;
        }
        .sidebar-content.scrollable::-webkit-scrollbar-thumb {
          background: var(--border-color);
          border-radius: 10px;
        }

        .project-info {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          background: var(--surface-accent);
          padding: 16px;
          border-radius: 12px;
          border-left: 3px solid var(--primary-color);
        }

        .toggle-tools-btn {
          background: rgba(255,255,255,0.05);
          border-radius: 8px;
          padding: 4px;
          color: var(--text-secondary);
          transition: all 0.2s;
        }

        .toggle-tools-btn:hover {
          background: rgba(255,255,255,0.1);
          color: var(--text-primary);
        }

        .label {
          font-size: 10px;
          text-transform: uppercase;
          letter-spacing: 1px;
          color: var(--text-secondary);
          margin-bottom: 4px;
        }

        .project-name {
          font-size: 16px;
          margin-bottom: 4px;
        }

        .developer-tag {
          font-size: 12px;
          color: var(--primary-color);
          font-weight: 500;
        }

        .tools-wrapper {
          display: flex;
          flex-direction: column;
          gap: 12px;
          overflow: hidden;
        }

        .prompt-section textarea {
          width: 100%;
          height: 60px;
          background: var(--surface-color);
          border: 1px solid var(--border-color);
          border-radius: 12px;
          padding: 10px;
          color: white;
          resize: none;
          margin-bottom: 8px;
          font-size: 13px;
          transition: border-color 0.3s;
        }

        .prompt-section textarea:focus {
          border-color: var(--primary-color);
        }

        .generate-btn {
          width: 100%;
          background: var(--primary-color);
          color: white;
          padding: 12px;
          border-radius: 12px;
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 8px;
          font-weight: 600;
        }

        .action-btn {
          width: 100%;
          padding: 10px;
          border-radius: 10px;
          display: flex;
          align-items: center;
          gap: 8px;
          font-size: 14px;
          color: var(--text-secondary);
        }

        .action-btn:hover {
          background: var(--surface-accent);
          color: var(--text-primary);
        }

        .action-btn.danger:hover {
          background: rgba(239, 68, 68, 0.1);
          color: #ef4444;
        }

        .divider {
          height: 1px;
          background: var(--border-color);
          margin: 8px 0;
        }

        .tool-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 10px;
          margin-top: 8px;
        }

        .tool-btn {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 10px;
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid var(--border-color);
          border-radius: 10px;
          color: var(--text-secondary);
          font-size: 13px;
          cursor: pointer;
          transition: all 0.2s;
        }

        .tool-btn:hover {
          background: rgba(255, 255, 255, 0.08);
          color: var(--text-primary);
          border-color: var(--text-secondary);
        }

        .primary-solid {
          background: var(--primary-color) !important;
          color: white !important;
          box-shadow: 0 10px 20px var(--primary-glow);
        }

        .primary-solid:hover {
          transform: translateY(-2px);
          filter: brightness(1.1);
        }

        .action-btn.secondary {
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid var(--border-color);
        }

        .action-btn.secondary:hover {
          background: rgba(255, 255, 255, 0.08);
          border-color: var(--text-secondary);
        }

        .donation-btn {
          background: rgba(236, 72, 153, 0.1) !important;
          color: #ec4899 !important;
          border: 1px solid rgba(236, 72, 153, 0.2) !important;
          justify-content: center;
          font-weight: 600;
        }

        .donation-btn:hover {
          background: rgba(236, 72, 153, 0.2) !important;
          transform: translateY(-1px);
        }

        .sidebar-footer {
          margin-top: auto;
          display: flex;
          justify-content: space-between;
          font-size: 12px;
          color: var(--text-secondary);
          flex-shrink: 0;
          padding-top: 20px;
        }

        .github-link {
          display: flex;
          align-items: center;
          gap: 6px;
          text-decoration: none;
          color: inherit;
        }

        /* Modal Styles */
        .modal-overlay {
          position: fixed;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          background: rgba(0,0,0,0.8);
          backdrop-filter: blur(8px);
          z-index: 1000;
          display: flex;
          align-items: center;
          justify-content: center;
          overflow-y: auto;
          padding: 20px;
        }

        .modal {
          width: 100%;
          max-width: 480px;
          background: rgba(30, 30, 40, 0.7);
          border-radius: 24px;
          box-shadow: 0 30px 60px rgba(0,0,0,0.8);
          display: flex;
          flex-direction: column;
          position: relative;
          max-height: calc(100vh - 40px);
        }

        .modal-header {
          padding: 32px 32px 20px;
          display: flex;
          justify-content: space-between;
          align-items: center;
          flex-shrink: 0;
        }

        .modal-body {
          padding: 0 28px 32px 32px;
          overflow-y: auto;
          flex: 1;
          scrollbar-gutter: stable;
        }

        .modal-body.scrollable::-webkit-scrollbar {
          width: 5px;
        }
        .modal-body.scrollable::-webkit-scrollbar-thumb {
          background: var(--primary-color);
          border-radius: 10px;
          opacity: 0.5;
        }
        .modal-body.scrollable::-webkit-scrollbar-thumb:hover {
          background: #a78bfa;
        }
        .modal-body.scrollable::-webkit-scrollbar-track {
          background: rgba(255, 255, 255, 0.03);
          border-radius: 10px;
        }

        .input-group {
          margin-bottom: 20px;
        }

        .input-group label {
          display: block;
          font-size: 12px;
          color: var(--text-secondary);
          margin-bottom: 8px;
        }

        .input-group select, .input-group input {
          width: 100%;
          padding: 12px;
          background: var(--surface-color);
          border: 1px solid var(--border-color);
          border-radius: 10px;
          color: white;
        }

        .modal-footer {
          padding: 0 32px 32px;
          flex-shrink: 0;
        }

        .close-btn {
          color: var(--text-secondary);
          padding: 8px;
          border-radius: 10px;
          transition: all 0.2s;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .close-btn:hover {
          background: var(--surface-accent);
          color: var(--text-primary);
        }

        .save-btn {
          width: 100%;
          padding: 14px;
          background: var(--primary-color);
          border-radius: 12px;
          color: white;
          font-weight: 600;
          transition: transform 0.2s, background 0.2s;
        }

        .save-btn:hover {
          transform: translateY(-2px);
          background: #8b5cf6;
        }
        .custom-scrollbar::-webkit-scrollbar {
          width: 3px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: var(--primary-color);
          border-radius: 10px;
        }
      `}</style>
    </>
  );
}
